name: Sync from GitLab

on:
  # Run this workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-from-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Clone GitLab repository
        run: |
          git clone --depth 1 https://gitlab.com/mcalec-dev/mcalec.dev temp-gitlab-repo

      - name: Copy public folder contents to root
        run: |
          # Remove everything except .git folder and GitHub workflow files
          find . -mindepth 1 -not -path "./.git*" -delete
          
          # Copy the public folder contents from GitLab repo to the root
          cp -R temp-gitlab-repo/public/* .
          
          # Clean up the temporary GitLab repository
          rm -rf temp-gitlab-repo

      - name: Commit and push changes
        run: |
          git add .
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync files from GitLab public folder"
            git push
          fi
