name: Sync from GitLab

on:
  # Run this workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-from-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Clone GitLab repository
        run: |
          git clone --depth 1 https://gitlab.com/mcalec-dev/mcalec.dev.git temp-gitlab-repo

      - name: Debug repository structure
        run: |
          echo "Listing the root content of the GitLab repository:"
          ls -la temp-gitlab-repo/
          
          # Find any public directories in the repository structure
          echo "Searching for 'public' directory in any location:"
          find temp-gitlab-repo -type d -name "public" | xargs -I{} ls -la "{}"

      - name: Copy folder contents to root
        run: |
          # Remove everything except .git folder and GitHub workflow files
          find . -mindepth 1 -not -path "./.git*" -delete
          
          # Look for public directories at any level in the repo structure
          PUBLIC_DIRS=$(find temp-gitlab-repo -type d -name "public")
          
          if [ -n "$PUBLIC_DIRS" ]; then
            # Use the first public directory found
            PUBLIC_DIR=$(echo "$PUBLIC_DIRS" | head -n 1)
            echo "Found public directory at: $PUBLIC_DIR"
            
            if [ -n "$(ls -A $PUBLIC_DIR)" ]; then
              echo "Copying files from $PUBLIC_DIR"
              cp -R $PUBLIC_DIR/* .
            else
              echo "Public directory is empty, nothing to copy"
              echo "Synced from GitLab at $(date)" > README.md
            fi
          else
            echo "No public directory found, copying from repository root"
            cp -R temp-gitlab-repo/* .
          fi
          
          # Clean up the temporary GitLab repository
          rm -rf temp-gitlab-repo

      - name: Commit and push changes
        run: |
          git add .
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync files from GitLab public folder"
            git push
          fi
