name: Sync from GitLab

on:
  # Run this workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-from-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Clone GitLab repository
        run: |
          git clone --depth 1 https://gitlab.com/mcalec-dev/mcalec.dev temp-gitlab-repo

      - name: Debug repository structure
        run: |
          echo "Listing the content of the GitLab repository:"
          ls -la temp-gitlab-repo/
          echo "Searching for 'public' directory in any location:"
          find temp-gitlab-repo -type d -name "public" | xargs -I{} echo "Found public dir: {}"

      - name: Copy folder contents to root
        run: |
          # Check if public directory exists
          if [ -d "temp-gitlab-repo/public" ]; then
            echo "Found public directory"
            SOURCE_DIR="temp-gitlab-repo/public"
          else
            echo "Public directory not found, using repository root"
            SOURCE_DIR="temp-gitlab-repo"
          fi
          
          # Remove everything except .git folder and GitHub workflow files
          find . -mindepth 1 -not -path "./.git*" -delete
          
          # Check if the source directory has any files
          if [ "$(ls -A ${SOURCE_DIR})" ]; then
            echo "Copying contents from ${SOURCE_DIR}"
            cp -R ${SOURCE_DIR}/* .
          else
            echo "Source directory is empty, nothing to copy"
            # Create a placeholder file to show the sync ran
            echo "Synced from GitLab at $(date)" > README.md
          fi
          
          # Add more detailed debugging
          echo "Contents of source directory:"
          ls -la ${SOURCE_DIR}
          
          # Clean up the temporary GitLab repository
          rm -rf temp-gitlab-repo

      - name: Commit and push changes
        run: |
          git add .
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync files from GitLab public folder"
            git push
          fi
